/** The fifty original trainer figures, shared byte-for-byte by all grades. */
export const AVATAR_NAMES = [
  "Pixel Hero",
  "Cat",
  "Owl",
  "Panda",
  "Wolf",
  "Red Panda",
  "Axolotl",
  "Chameleon",
  "Penguin",
  "Skeleton",
  "Baby Dragon",
  "Phoenix",
  "Unicorn",
  "Griffin",
  "Kraken",
  "Wizard",
  "Knight",
  "Ninja",
  "Pirate",
  "Viking",
  "Astronaut",
  "Alien",
  "Robot",
  "Space Cat",
  "Diamond Gem",
  "Mushroom Sprite",
  "Flame Spirit",
  "Ice Crystal",
  "Storm Cloud",
  "Leaf Guardian",
  "Taco",
  "Donut",
  "Cactus",
  "Coffee Cup",
  "Book",
  "Fox",
  "Slime",
  "Treasure Chest",
  "Potion Bottle",
  "Shield",
  "Star",
  "Moon",
  "Dice",
  "Lightning Bolt",
  "Goblin",
  "Yeti",
  "Ghost",
  "Cyclops",
  "Rocket",
  "Sword"
] as const;

export function avatarPath(avatar: number): string {
  const n = Number.isInteger(avatar) && avatar >= 1 && avatar <= 50 ? avatar : 1;
  return `/avatars/${String(n).padStart(2, "0")}.png`;
}
