#!/usr/bin/env python3
"""G2 "The Spill" — chapters ch09–ch15 (Act 2: the taking · Act 3: the filling).

Authored by Fable per docs/handover/20_g2n_the_spill.md. The Blank speaks from
ch12 ONLY in single stolen words (corpus vocabulary by design — bible §4.3).
Note: story.json is the authoritative artifact; these scripts are authoring
provenance (an auto-gloss convergence pass added bank-escape glosses in place).
"""
import json

SP = "content/corpus/stories/g2.st.the-spill/story.json"
CP = "content/corpus/stories/g2.st.the-spill/comprehension.json"
CH = "g2.st.the-spill"


def sc(ch, n, speaker, en, de, glosses, slots=None):
    return {"id": f"{CH}.{ch}.s{n:03d}", "speaker": speaker, "textEn": en, "scaffoldDe": de,
            "glosses": [{"word": w, "de": d, "scope": None} for w, d in glosses],
            "audio": None, "taskSlots": slots or [], "next": None}


def slot(kind, item):
    return {"slot": kind, "itemId": item, "variantKey": None}


def ci(cid, prompt, full, distractors, gloss, hint_de, explain_de):
    return {"id": cid, "rev": 1, "difficulty": 1, "format": "multiple-choice",
            "prompt": {"text": prompt, "lang": "en", "blanks": 0},
            "answers": [{"text": full, "tier": "full"}], "direction": None,
            "distractors": distractors, "pairs": [], "groups": [],
            "gloss": [{"word": w, "de": d, "scope": None} for w, d in gloss],
            "hintDe": hint_de, "hintEn": None, "explainDe": explain_de,
            "explainEn": None, "strict": False}


# ── ch09 · u09 "The Eaten Menu" — canteen comedy, then the menu goes ──
ch09 = ("The Eaten Menu", "Die gegessene Speisekarte", [
    sc("ch09", 1, "narrator", "Lunchtime. The canteen smells wonderful and slightly impossible.",
       "Mittagszeit. Die Kantine riecht wunderbar und leicht unmöglich.",
       [("lunchtime", "Mittagszeit"), ("canteen", "Kantine"), ("smells", "riecht"), ("slightly", "leicht"), ("impossible", "unmöglich")]),
    sc("ch09", 2, "tarik", "The soup has WEATHER in it. A small cloud. It is raining into my soup and I am NOT complaining.",
       "In der Suppe ist WETTER. Eine kleine Wolke. Es regnet in meine Suppe, und ich beschwere mich NICHT.",
       [("soup", "Suppe"), ("weather", "Wetter"), ("cloud", "Wolke"), ("raining", "regnet"), ("complaining", "beschweren")]),
    sc("ch09", 3, "narrator", "The cookbook shelf leaked into the kitchen. The man at the pots is fighting a recipe for storybook stew — and losing politely.",
       "Das Kochbuch-Regal hat in die Küche geleckt. Der Mann an den Töpfen kämpft mit einem Rezept für Geschichten-Eintopf — und verliert höflich.",
       [("cookbook", "Kochbuch"), ("kitchen", "Küche"), ("pots", "Töpfe"), ("recipe", "Rezept"), ("stew", "Eintopf"), ("politely", "höflich"), ("leaked", "geleckt"), ("losing", "verliert")]),
    sc("ch09", 4, "emma", "The man with the tall white hat needs help. What is his job called? Find the word!",
       "Der Mann mit der hohen weißen Mütze braucht Hilfe. Wie heißt sein Beruf? Finde das Wort!",
       [("tall", "hoch"), ("hat", "Mütze"), ("job", "Beruf"), ("needs", "braucht"), ("help", "Hilfe")],
       [slot("name-it", "g2u09.w.chef")]),
    sc("ch09", 5, "tarik", "The stew wants a green vegetable with many leaves. Find it!",
       "Der Eintopf will ein grünes Gemüse mit vielen Blättern. Finde es!",
       [("stew", "Eintopf"), ("vegetable", "Gemüse"), ("leaves", "Blätter"), ("green", "grün")],
       [slot("name-it", "g2u09.w.cabbage")]),
    sc("ch09", 6, "narrator", "Then the room goes quiet. Not the nice quiet. The menu board is empty — every dish, every price, gone.",
       "Dann wird der Raum still. Nicht die schöne Stille. Die Speisekarten-Tafel ist leer — jedes Gericht, jeder Preis, weg.",
       [("room", "Raum"), ("quiet", "still"), ("menu board", "Speisekarten-Tafel"), ("empty", "leer"), ("dish", "Gericht"), ("price", "Preis"), ("gone", "weg")]),
    sc("ch09", 7, "emma", "Nobody can order what nobody can NAME. Chef — we rebuild your menu, word by word.",
       "Niemand kann bestellen, was niemand BENENNEN kann. Chef — wir bauen deine Speisekarte wieder auf, Wort für Wort.",
       [("nobody", "niemand"), ("order", "bestellen"), ("name", "benennen"), ("rebuild", "wieder aufbauen"), ("menu", "Speisekarte"), ("word", "Wort")]),
    sc("ch09", 8, "jona", "Is there any soup left? Say it right — carefully. Words are food here.",
       "Ist noch Suppe da? Sag es richtig — vorsichtig. Wörter sind hier Essen.",
       [("soup", "Suppe"), ("left", "übrig"), ("carefully", "vorsichtig"), ("words", "Wörter"), ("food", "Essen"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u09.gi.some-any.cp.001")]),
    sc("ch09", 9, "tarik", "And I want the big pizza, not the small... you know. Say it right!",
       "Und ich will die große Pizza, nicht die kleine... du weißt schon. Sag es richtig!",
       [("pizza", "Pizza"), ("small", "klein"), ("know", "weißt"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u09.gi.one-ones.cp.001")]),
    sc("ch09", 10, "narrator", "The menu fills back up. The chef writes each returned word twice — once on the board, once in his heart.",
       "Die Speisekarte füllt sich wieder. Der Chef schreibt jedes zurückgekehrte Wort zweimal — einmal auf die Tafel, einmal in sein Herz.",
       [("fills", "füllt sich"), ("returned", "zurückgekehrt"), ("twice", "zweimal"), ("board", "Tafel"), ("heart", "Herz"), ("menu", "Speisekarte"), ("word", "Wort")],
       [slot("recap", "g2u09.ci.the-menu.mc.001")]),
    sc("ch09", 11, "tarik", "Review: the storybook stew is five stars. The rain cloud is a bit much. Four stars.",
       "Bewertung: Der Geschichten-Eintopf bekommt fünf Sterne. Die Regenwolke ist ein bisschen viel. Vier Sterne.",
       [("review", "Bewertung"), ("stars", "Sterne"), ("rain cloud", "Regenwolke"), ("a bit much", "ein bisschen viel"), ("stew", "Eintopf")]),
    sc("ch09", 12, "jona", "It took the menu at lunch. The fullest hour. It is getting braver — or hungrier.",
       "Es hat die Speisekarte zur Mittagszeit genommen. Zur vollsten Stunde. Es wird mutiger — oder hungriger.",
       [("took", "genommen"), ("menu", "Speisekarte"), ("fullest", "vollste"), ("hour", "Stunde"), ("braver", "mutiger"), ("hungrier", "hungriger")]),
])
ci09 = ci("g2u09.ci.the-menu.mc.001", "Why can nobody order lunch?",
          "The menu words are gone.",
          ["The canteen is closed.", "The chef is on holiday.", "The soup is cold."],
          [("order", "bestellen"), ("menu", "Speisekarte"), ("gone", "weg"), ("canteen", "Kantine"), ("closed", "geschlossen"), ("chef", "Chef"), ("holiday", "Urlaub"), ("soup", "Suppe"), ("cold", "kalt"), ("words", "Wörter"), ("lunch", "Mittagessen"), ("nobody", "niemand")],
          "Schau auf die Tafel in der Kantine — was fehlt?",
          "Die leere Stelle hat alle Wörter der Speisekarte genommen — und was niemand benennen kann, kann niemand bestellen. Ihr schreibt sie Wort für Wort zurück."),

# ── ch10 · u10 "The Photo With a Gap" — THE HEART ──
ch10 = ("The Photo With a Gap", "Das Foto mit der Lücke", [
    sc("ch10", 1, "narrator", "Saturday. Jona invites the team home — a small flat, a big table, and walls full of photos.",
       "Samstag. Jona lädt das Team zu sich nach Hause ein — eine kleine Wohnung, ein großer Tisch und Wände voller Fotos.",
       [("Saturday", "Samstag"), ("invites", "lädt ein"), ("flat", "Wohnung"), ("table", "Tisch"), ("walls", "Wände"), ("photos", "Fotos"), ("home", "nach Hause"), ("team", "Team")]),
    sc("ch10", 2, "jona", "My mum cooks too much when she is happy. She is very happy today. Bring hunger.",
       "Meine Mama kocht zu viel, wenn sie glücklich ist. Heute ist sie sehr glücklich. Bringt Hunger mit.",
       [("mum", "Mama"), ("cooks", "kocht"), ("happy", "glücklich"), ("hunger", "Hunger"), ("bring", "bringt")]),
    sc("ch10", 3, "narrator", "The photos climb the wall by year. School photos, birthdays, a beach. And in photo after photo — a pale gap.",
       "Die Fotos klettern die Wand hoch, Jahr für Jahr. Schulfotos, Geburtstage, ein Strand. Und auf Foto um Foto — eine blasse Lücke.",
       [("climb", "klettern"), ("year", "Jahr"), ("birthdays", "Geburtstage"), ("beach", "Strand"), ("pale", "blass"), ("gap", "Lücke"), ("photos", "Fotos"), ("wall", "Wand")]),
    sc("ch10", 4, "emma", "Jona. Where are YOU in these pictures?",
       "Jona. Wo bist DU auf diesen Bildern?",
       [("pictures", "Bilder")]),
    sc("ch10", 5, "jona", "The years in the book took me out of them. My family remembers me. The paper does not.",
       "Die Jahre im Buch haben mich aus ihnen herausgenommen. Meine Familie erinnert sich an mich. Das Papier nicht.",
       [("years", "Jahre"), ("book", "Buch"), ("took", "herausgenommen"), ("family", "Familie"), ("remembers", "erinnert sich"), ("paper", "Papier")]),
    sc("ch10", 6, "tarik", "Then we put you back. Person by person, name by name. Who is the woman with your smile? Find the word!",
       "Dann setzen wir dich zurück. Person für Person, Name für Name. Wer ist die Frau mit deinem Lächeln? Finde das Wort!",
       [("put", "zurücksetzen"), ("person", "Person"), ("name", "Name"), ("woman", "Frau"), ("smile", "Lächeln")],
       [slot("name-it", "g2u10.w.auntie")]),
    sc("ch10", 7, "jona", "There is a word for how my family looks at me since I came back. Find it.",
       "Es gibt ein Wort dafür, wie meine Familie mich anschaut, seit ich zurück bin. Finde es.",
       [("family", "Familie"), ("looks at", "anschaut"), ("since", "seit"), ("came back", "zurückgekommen"), ("word", "Wort")],
       [slot("name-it", "g2u10.w.to-be-proud-of")]),
    sc("ch10", 8, "emma", "And all these people on the wall — there is a word for what they are to you. Find it!",
       "Und all diese Leute an der Wand — es gibt ein Wort dafür, was sie für dich sind. Finde es!",
       [("people", "Leute"), ("wall", "Wand"), ("word", "Wort")],
       [slot("name-it", "g2u10.w.to-be-related-to")]),
    sc("ch10", 9, "narrator", "Each named person sharpens in the photos. And beside them, faint as breath on glass, a boy's outline begins.",
       "Jede benannte Person wird auf den Fotos schärfer. Und neben ihnen, zart wie Atem auf Glas, beginnt der Umriss eines Jungen.",
       [("named", "benannt"), ("sharpens", "wird schärfer"), ("faint", "zart"), ("breath", "Atem"), ("glass", "Glas"), ("outline", "Umriss"), ("begins", "beginnt"), ("person", "Person"), ("photos", "Fotos"), ("boy", "Junge")]),
    sc("ch10", 10, "emma", "You must say the names out loud, Jona. It only works with your voice. Say it right!",
       "Du musst die Namen laut sagen, Jona. Es funktioniert nur mit deiner Stimme. Sag es richtig!",
       [("must", "musst"), ("names", "Namen"), ("out loud", "laut"), ("works", "funktioniert"), ("voice", "Stimme"), ("say", "sag"), ("right", "richtig"), ("only", "nur")],
       [slot("fix-it", "g2u10.gi.must.cp.001")]),
    sc("ch10", 11, "jona", "I like being in pictures. I forgot that too. Say it right!",
       "Ich mag es, auf Bildern zu sein. Auch das habe ich vergessen. Sag es richtig!",
       [("like", "mag"), ("being", "sein"), ("pictures", "Bilder"), ("forgot", "vergessen"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u10.gi.like-ing.cp.001")]),
    sc("ch10", 12, "narrator", "Then Emma holds two things side by side: the pale gap in the photo. The pale smudge from school. The same paleness.",
       "Dann hält Emma zwei Dinge nebeneinander: die blasse Lücke im Foto. Den blassen Fleck aus der Schule. Dieselbe Blässe.",
       [("holds", "hält"), ("side by side", "nebeneinander"), ("gap", "Lücke"), ("smudge", "Fleck"), ("paleness", "Blässe"), ("pale", "blass"), ("photo", "Foto"), ("things", "Dinge"), ("school", "Schule")],
       [slot("recap", "g2u10.ci.the-gap.mc.001")]),
    sc("ch10", 13, "jona", "It is made of what I erased. All those words. All those years. ... It is made of me.",
       "Es besteht aus dem, was ich wegradiert habe. All die Wörter. All die Jahre. ... Es besteht aus mir.",
       [("made of", "besteht aus"), ("erased", "wegradiert"), ("words", "Wörter"), ("years", "Jahre")]),
    sc("ch10", 14, "tarik", "Then it is not a hunt. It never was. ... Your mum says dinner is ready. Both of you, come eat.",
       "Dann ist es keine Jagd. War es nie. ... Deine Mama sagt, das Essen ist fertig. Kommt essen, alle beide.",
       [("hunt", "Jagd"), ("never", "nie"), ("dinner", "Essen"), ("ready", "fertig"), ("mum", "Mama"), ("says", "sagt"), ("come", "kommt"), ("eat", "essen")]),
])
ci10 = ci("g2u10.ci.the-gap.mc.001", "What do the gap in the photos and the smudge at school have in common?",
          "They are the same paleness.",
          ["They are both photos.", "They are both at school.", "They are both loud."],
          [("gap", "Lücke"), ("photos", "Fotos"), ("smudge", "Fleck"), ("school", "Schule"), ("paleness", "Blässe"), ("same", "dieselbe"), ("loud", "laut"), ("have in common", "gemeinsam haben")],
          "Emma hält Foto und Fleck nebeneinander — was sieht sie?",
          "Die Lücke in Jonas Fotos und der Fleck in der Schule haben dieselbe Blässe: Die leere Stelle besteht aus allem, was Jona wegradiert hat — auch aus ihm selbst. Das ist das Herz der Geschichte."),

# ── ch11 · u11 "Where the Blank Lives" — the nest, not a lair ──
ch11 = ("Where the Blank Lives", "Wo die leere Stelle wohnt", [
    sc("ch11", 1, "narrator", "Monday, after school. The corridor to the old storeroom. The animals were right: it is very, very quiet here.",
       "Montag, nach der Schule. Der Gang zur alten Abstellkammer. Die Tiere hatten recht: Es ist sehr, sehr still hier.",
       [("Monday", "Montag"), ("corridor", "Gang"), ("storeroom", "Abstellkammer"), ("animals", "Tiere"), ("right", "recht"), ("quiet", "still"), ("school", "Schule"), ("old", "alt")]),
    sc("ch11", 2, "emma", "This is where the book lived for years, before Frau Berger's shelf. And this is where IT lives now.",
       "Hier hat das Buch jahrelang gewohnt, vor Frau Bergers Regal. Und hier wohnt jetzt ES.",
       [("book", "Buch"), ("lived", "gewohnt"), ("years", "jahrelang"), ("shelf", "Regal"), ("lives", "wohnt")]),
    sc("ch11", 3, "narrator", "The door is not locked. Inside: not a lair. A room, arranged with terrible care.",
       "Die Tür ist nicht abgeschlossen. Drinnen: kein Versteck. Ein Zimmer, mit schrecklicher Sorgfalt eingerichtet.",
       [("door", "Tür"), ("locked", "abgeschlossen"), ("inside", "drinnen"), ("lair", "Versteck"), ("room", "Zimmer"), ("arranged", "eingerichtet"), ("care", "Sorgfalt"), ("terrible", "schrecklich")]),
    sc("ch11", 4, "tarik", "The orange from the wall — painted on a box. The menu words — stacked like books. And a party plan, smoothed out.",
       "Das Orange von der Wand — auf eine Kiste gemalt. Die Speisekarten-Wörter — gestapelt wie Bücher. Und ein Partyplan, glatt gestrichen.",
       [("orange", "orange"), ("painted", "gemalt"), ("box", "Kiste"), ("menu", "Speisekarte"), ("stacked", "gestapelt"), ("party", "Party"), ("plan", "Plan"), ("smoothed", "glatt gestrichen"), ("wall", "Wand"), ("words", "Wörter"), ("books", "Bücher")]),
    sc("ch11", 5, "emma", "It keeps everything. Like someone keeping what nobody else wanted. Where does it sleep — find the word for the room under a house!",
       "Es hebt alles auf. Wie jemand, der aufhebt, was sonst niemand wollte. Wo schläft es — finde das Wort für den Raum unter einem Haus!",
       [("keeps", "hebt auf"), ("nobody", "niemand"), ("wanted", "wollte"), ("sleep", "schlafen"), ("house", "Haus"), ("room", "Raum"), ("under", "unter"), ("word", "Wort"), ("someone", "jemand"), ("everything", "alles"), ("find", "finde")],
       [slot("name-it", "g2u11.w.cellar")]),
    sc("ch11", 6, "tarik", "It made a bed area from a... tall thing with doors, for clothes. Find the word!",
       "Es hat sich einen Schlafplatz gebaut aus einem... hohen Ding mit Türen, für Kleidung. Finde das Wort!",
       [("bed", "Schlafplatz"), ("tall", "hoch"), ("doors", "Türen"), ("clothes", "Kleidung"), ("thing", "Ding"), ("word", "Wort"), ("made", "gebaut"), ("find", "finde")],
       [slot("name-it", "g2u11.w.cupboard")]),
    sc("ch11", 7, "jona", "And a soft place to sit, by the window. The big one, for reading. Find it!",
       "Und einen weichen Platz zum Sitzen, am Fenster. Den großen, zum Lesen. Finde ihn!",
       [("soft", "weich"), ("place", "Platz"), ("sit", "sitzen"), ("window", "Fenster"), ("reading", "Lesen"), ("big", "groß"), ("find", "finde")],
       [slot("name-it", "g2u11.w.armchair")]),
    sc("ch11", 8, "emma", "Whose plan is that on the shelf? Careful with the words here. Say it right!",
       "Wessen Plan ist das im Regal? Vorsicht mit den Wörtern hier. Sag es richtig!",
       [("whose", "wessen"), ("plan", "Plan"), ("shelf", "Regal"), ("careful", "Vorsicht"), ("words", "Wörter"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u11.gi.possessive-pronouns.cp.001")]),
    sc("ch11", 9, "jona", "And the words on the shelf — they are not ours anymore. They are... hers? His? Its. Say it right!",
       "Und die Wörter im Regal — sie gehören nicht mehr uns. Sie sind... ihre? Seine? Sag es richtig!",
       [("words", "Wörter"), ("shelf", "Regal"), ("ours", "unsere"), ("anymore", "nicht mehr"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u11.gi.possessive-pronouns.cp.002")]),
    sc("ch11", 10, "narrator", "Nobody fights. Nobody shouts. Everyone stands in the small kept room and goes quiet.",
       "Niemand kämpft. Niemand schreit. Alle stehen in dem kleinen, gehüteten Zimmer und werden still.",
       [("fights", "kämpft"), ("shouts", "schreit"), ("stands", "stehen"), ("kept", "gehütet"), ("quiet", "still"), ("room", "Zimmer"), ("small", "klein"), ("nobody", "niemand"), ("everyone", "alle")],
       [slot("recap", "g2u11.ci.the-nest.mc.001")]),
    sc("ch11", 11, "jona", "I know this room. I lived in one like it. ... We are not going to chase it. We are going to invite it.",
       "Ich kenne dieses Zimmer. Ich habe in so einem gewohnt. ... Wir werden es nicht jagen. Wir werden es einladen.",
       [("know", "kenne"), ("room", "Zimmer"), ("lived", "gewohnt"), ("chase", "jagen"), ("invite", "einladen")]),
    sc("ch11", 12, "narrator", "On the way out, Tarik leaves his second-favourite pencil on the armchair. Just in case.",
       "Beim Hinausgehen legt Tarik seinen zweitliebsten Bleistift auf den Sessel. Nur für den Fall.",
       [("on the way out", "beim Hinausgehen"), ("leaves", "legt hin"), ("second-favourite", "zweitliebster"), ("pencil", "Bleistift"), ("armchair", "Sessel"), ("just in case", "nur für den Fall")]),
])
ci11 = ci("g2u11.ci.the-nest.mc.001", "What does the team find in the storeroom?",
          "The taken things, kept with care.",
          ["A dangerous animal.", "An empty room.", "The school books."],
          [("storeroom", "Abstellkammer"), ("taken", "genommen"), ("things", "Dinge"), ("kept", "aufgehoben"), ("care", "Sorgfalt"), ("dangerous", "gefährlich"), ("animal", "Tier"), ("empty", "leer"), ("room", "Zimmer"), ("find", "finden"), ("team", "Team"), ("school", "Schule"), ("books", "Bücher")],
          "Kein Versteck — was ist das Zimmer wirklich?",
          "Die leere Stelle hebt alles Genommene sorgfältig auf — wie jemand, der behält, was sonst niemand wollte. Darum beschließt das Team: nicht jagen, sondern einladen."),

# ── ch12 · u12 "The First Word Back" — the Blank speaks ──
ch12 = ("The First Word Back", "Das erste Wort zurück", [
    sc("ch12", 1, "narrator", "The quiet room, after school. The team sits on the floor with biscuits and does absolutely nothing threatening.",
       "Das stille Zimmer, nach der Schule. Das Team sitzt am Boden mit Keksen und macht absolut nichts Bedrohliches.",
       [("quiet", "still"), ("room", "Zimmer"), ("floor", "Boden"), ("biscuits", "Kekse"), ("absolutely", "absolut"), ("threatening", "bedrohlich"), ("team", "Team"), ("school", "Schule"), ("nothing", "nichts"), ("sits", "sitzt")]),
    sc("ch12", 2, "jona", "It is here. In the corner. Do not look straight at it. Talk to each other, not at it.",
       "Es ist hier. In der Ecke. Schaut es nicht direkt an. Redet miteinander, nicht auf es ein.",
       [("corner", "Ecke"), ("straight", "direkt"), ("talk", "redet"), ("each other", "miteinander"), ("look", "schaut")]),
    sc("ch12", 3, "emma", "So we name feelings. Out loud. Mine first: I have been nervous all day.",
       "Also benennen wir Gefühle. Laut. Meins zuerst: Ich bin schon den ganzen Tag nervös.",
       [("name", "benennen"), ("feelings", "Gefühle"), ("out loud", "laut"), ("nervous", "nervös"), ("first", "zuerst"), ("day", "Tag"), ("mine", "meins")]),
    sc("ch12", 4, "narrator", "The pale patch in the corner turns — the way a listener turns. With every named feeling, it is one shade less pale.",
       "Der blasse Fleck in der Ecke dreht sich — wie ein Zuhörer sich dreht. Mit jedem benannten Gefühl ist er eine Spur weniger blass.",
       [("pale", "blass"), ("patch", "Fleck"), ("turns", "dreht sich"), ("listener", "Zuhörer"), ("named", "benannt"), ("shade", "Spur"), ("feeling", "Gefühl"), ("corner", "Ecke"), ("less", "weniger")]),
    sc("ch12", 5, "tarik", "When my head hurts and everything is too loud — what is that called? Find the word!",
       "Wenn mein Kopf wehtut und alles zu laut ist — wie heißt das? Finde das Wort!",
       [("head", "Kopf"), ("hurts", "wehtut"), ("loud", "laut"), ("called", "heißt"), ("everything", "alles"), ("word", "Wort"), ("find", "finde")],
       [slot("name-it", "g2u12.w.headache")]),
    sc("ch12", 6, "emma", "And when someone stays with you until it is better — there is a word for how that person is. Find it!",
       "Und wenn jemand bei dir bleibt, bis es besser ist — es gibt ein Wort dafür, wie diese Person ist. Finde es!",
       [("someone", "jemand"), ("stays", "bleibt"), ("better", "besser"), ("person", "Person"), ("word", "Wort"), ("until", "bis"), ("find", "finde")],
       [slot("name-it", "g2u12.w.helpful")]),
    sc("ch12", 7, "jona", "I have felt empty before. Not sad — empty. There is a difference. Say it right!",
       "Ich habe mich schon leer gefühlt. Nicht traurig — leer. Da ist ein Unterschied. Sag es richtig!",
       [("felt", "gefühlt"), ("empty", "leer"), ("sad", "traurig"), ("difference", "Unterschied"), ("before", "schon einmal"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u12.gi.present-perfect.cp.001")]),
    sc("ch12", 8, "emma", "And it has never hurt anyone. All this time. Say that too — it matters. Say it right!",
       "Und es hat nie jemandem wehgetan. Die ganze Zeit. Sag auch das — es ist wichtig. Sag es richtig!",
       [("never", "nie"), ("hurt", "wehgetan"), ("anyone", "irgendjemand"), ("matters", "ist wichtig"), ("time", "Zeit"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u12.gi.present-perfect.cp.002")]),
    sc("ch12", 9, "narrator", "Then, from the corner, in a voice like a page turning — a single word. A stolen one, given back as a question:",
       "Dann, aus der Ecke, mit einer Stimme wie eine Seite, die sich umblättert — ein einziges Wort. Ein gestohlenes, zurückgegeben als Frage:",
       [("voice", "Stimme"), ("page", "Seite"), ("turning", "umblättern"), ("single", "einzig"), ("stolen", "gestohlen"), ("given back", "zurückgegeben"), ("question", "Frage"), ("word", "Wort"), ("corner", "Ecke")]),
    sc("ch12", 10, "blank", "...glad?",
       "...froh?",
       [("glad", "froh")]),
    sc("ch12", 11, "tarik", "You can keep that one.",
       "Das darfst du behalten.",
       [("keep", "behalten")],
       [slot("recap", "g2u12.ci.first-word.mc.001")]),
    sc("ch12", 12, "narrator", "Nobody chases anything, ever again. That is decided without a vote, in the quietest room of the school.",
       "Niemand jagt mehr irgendetwas, nie wieder. Das wird ohne Abstimmung beschlossen, im stillsten Zimmer der Schule.",
       [("chases", "jagt"), ("decided", "beschlossen"), ("vote", "Abstimmung"), ("quietest", "stillste"), ("room", "Zimmer"), ("nobody", "niemand"), ("school", "Schule"), ("again", "wieder")]),
])
ci12 = ci("g2u12.ci.first-word.mc.001", "What is the blank's first word?",
          "Glad.",
          ["Help.", "Stop.", "Mine."],
          [("blank", "leere Stelle"), ("first", "erste"), ("word", "Wort"), ("glad", "froh"), ("stop", "stopp"), ("mine", "meins"), ("help", "Hilfe")],
          "Ein einziges gestohlenes Wort, als Frage zurückgegeben...",
          "Die leere Stelle spricht zum ersten Mal — nur in Wörtern, die sie genommen hat. Ihr erstes Wort zurück ist 'froh?' — und Tarik schenkt es ihr. Ab jetzt wird nicht mehr gejagt."),

# ── ch13 · u13 "The Grey Day" — the rule played ──
ch13 = ("The Grey Day", "Der graue Tag", [
    sc("ch13", 1, "narrator", "Wednesday arrives with no colour in it. The sky over the school is grey. The walls are grey. The JUICE is grey.",
       "Der Mittwoch kommt ganz ohne Farbe. Der Himmel über der Schule ist grau. Die Wände sind grau. Sogar der SAFT ist grau.",
       [("Wednesday", "Mittwoch"), ("colour", "Farbe"), ("sky", "Himmel"), ("grey", "grau"), ("walls", "Wände"), ("juice", "Saft"), ("school", "Schule")]),
    sc("ch13", 2, "emma", "Something upset it. After the best day, the worst — that is how feelings work when they are new.",
       "Etwas hat sie aufgewühlt. Nach dem besten Tag der schlimmste — so funktionieren Gefühle, wenn sie neu sind.",
       [("upset", "aufgewühlt"), ("worst", "schlimmste"), ("feelings", "Gefühle"), ("new", "neu"), ("work", "funktionieren"), ("best", "beste"), ("day", "Tag"), ("something", "etwas")]),
    sc("ch13", 3, "jona", "It is not taking. It is leaking — the grey is its feeling, spilling out. We bring colour back with weather words.",
       "Sie nimmt nichts. Sie leckt — das Grau ist ihr Gefühl, es läuft über. Wir bringen die Farbe mit Wetterwörtern zurück.",
       [("taking", "nehmen"), ("leaking", "lecken"), ("grey", "grau"), ("feeling", "Gefühl"), ("spilling", "überlaufen"), ("colour", "Farbe"), ("weather", "Wetter"), ("words", "Wörter"), ("back", "zurück")]),
    sc("ch13", 4, "tarik", "The sky when it is full of white sheep-shapes — find the word!",
       "Der Himmel, wenn er voller weißer Schaf-Formen ist — finde das Wort!",
       [("sky", "Himmel"), ("white", "weiß"), ("sheep", "Schaf"), ("shapes", "Formen"), ("word", "Wort"), ("find", "finde"), ("full", "voller")],
       [slot("name-it", "g2u13.w.cloudy")]),
    sc("ch13", 5, "emma", "And the opposite — when the light is strong and everything shines. Find it!",
       "Und das Gegenteil — wenn das Licht stark ist und alles leuchtet. Finde es!",
       [("opposite", "Gegenteil"), ("light", "Licht"), ("strong", "stark"), ("shines", "leuchtet"), ("everything", "alles"), ("find", "finde")],
       [slot("name-it", "g2u13.w.bright")]),
    sc("ch13", 6, "jona", "And the soft grey air you cannot see through, early in the morning. Find it!",
       "Und die weiche graue Luft, durch die man nicht sehen kann, früh am Morgen. Finde sie!",
       [("soft", "weich"), ("air", "Luft"), ("see through", "durchsehen"), ("early", "früh"), ("morning", "Morgen"), ("grey", "grau"), ("find", "finde")],
       [slot("name-it", "g2u13.w.fog")]),
    sc("ch13", 7, "narrator", "Each weather word paints a stripe of the world back in. The juice recovers first. Tarik checks. Twice.",
       "Jedes Wetterwort malt einen Streifen der Welt zurück. Der Saft erholt sich zuerst. Tarik prüft es. Zweimal.",
       [("weather", "Wetter"), ("word", "Wort"), ("paints", "malt"), ("stripe", "Streifen"), ("world", "Welt"), ("recovers", "erholt sich"), ("checks", "prüft"), ("twice", "zweimal"), ("first", "zuerst"), ("juice", "Saft")]),
    sc("ch13", 8, "emma", "Tomorrow the sun will come back. Say it to the room — like you mean it. Say it right!",
       "Morgen wird die Sonne zurückkommen. Sag es zum Zimmer — als ob du es ernst meinst. Sag es richtig!",
       [("tomorrow", "morgen"), ("sun", "Sonne"), ("come back", "zurückkommen"), ("mean it", "ernst meinen"), ("room", "Zimmer"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u13.gi.will-future.cp.001")]),
    sc("ch13", 9, "tarik", "And it will not be grey forever. Promise it that too. Say it right!",
       "Und es wird nicht für immer grau sein. Versprich ihr auch das. Sag es richtig!",
       [("forever", "für immer"), ("promise", "versprich"), ("grey", "grau"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u13.gi.will-future.cp.002")]),
    sc("ch13", 10, "narrator", "The class learns the rule and writes it nowhere, because everyone understands it now: chased, it takes more. Included, it takes less.",
       "Die Klasse lernt die Regel und schreibt sie nirgendwo auf, weil sie jetzt alle verstehen: Gejagt nimmt sie mehr. Dazugehörig nimmt sie weniger.",
       [("learns", "lernt"), ("rule", "Regel"), ("nowhere", "nirgendwo"), ("understands", "verstehen"), ("chased", "gejagt"), ("included", "dazugehörig"), ("takes", "nimmt"), ("class", "Klasse"), ("more", "mehr"), ("less", "weniger"), ("writes", "schreibt")],
       [slot("recap", "g2u13.ci.the-rule.mc.001")]),
    sc("ch13", 11, "narrator", "From that day, kids leave it words on purpose. Small ones. Spare ones. The lost-property box fills with syllables.",
       "Von diesem Tag an lassen die Kinder ihr absichtlich Wörter da. Kleine. Übrige. Die Fundkiste füllt sich mit Silben.",
       [("on purpose", "absichtlich"), ("spare", "übrig"), ("lost-property box", "Fundkiste"), ("syllables", "Silben"), ("kids", "Kinder"), ("words", "Wörter"), ("fills", "füllt sich"), ("small", "klein"), ("leave", "dalassen"), ("day", "Tag")]),
])
ci13 = ci("g2u13.ci.the-rule.mc.001", "What is the rule the class learns?",
          "Chased, it takes more — included, it takes less.",
          ["Grey days are normal.", "Weather words are magic.", "The juice is always grey."],
          [("rule", "Regel"), ("chased", "gejagt"), ("included", "dazugehörig"), ("takes", "nimmt"), ("grey", "grau"), ("weather", "Wetter"), ("magic", "Magie"), ("juice", "Saft"), ("normal", "normal"), ("class", "Klasse"), ("learn", "lernen"), ("more", "mehr"), ("less", "weniger"), ("days", "Tage"), ("always", "immer"), ("words", "Wörter")],
          "Was passiert, wenn man sie jagt — und was, wenn sie dazugehört?",
          "Der graue Tag lehrt die stille Regel der Kampagne: Gejagt nimmt die leere Stelle mehr, dazugehörig weniger. Die Kinder lassen ihr von jetzt an absichtlich kleine Wörter da."),

# ── ch14 · u14 "Sports Day" — the rescue inversion ──
ch14 = ("Sports Day", "Der Sporttag", [
    sc("ch14", 1, "narrator", "Sports day! Flags, whistles, three hundred kids — the loudest the school has been all year.",
       "Sporttag! Fahnen, Pfeifen, dreihundert Kinder — so laut war die Schule das ganze Jahr nicht.",
       [("flags", "Fahnen"), ("whistles", "Pfeifen"), ("three hundred", "dreihundert"), ("loudest", "am lautesten"), ("kids", "Kinder"), ("school", "Schule"), ("year", "Jahr")]),
    sc("ch14", 2, "tarik", "I have already signed us up for EVERYTHING. The running, the jumping, the thing with the sacks!",
       "Ich habe uns schon für ALLES angemeldet. Das Laufen, das Springen, das Ding mit den Säcken!",
       [("signed", "angemeldet"), ("running", "Laufen"), ("jumping", "Springen"), ("sacks", "Säcke"), ("everything", "alles"), ("already", "schon"), ("thing", "Ding")]),
    sc("ch14", 3, "emma", "The big race with teams and a winner — find the word!",
       "Das große Rennen mit Teams und einem Sieger — finde das Wort!",
       [("race", "Rennen"), ("winner", "Sieger"), ("teams", "Teams"), ("word", "Wort"), ("find", "finde"), ("big", "groß")],
       [slot("name-it", "g2u14.w.competition")]),
    sc("ch14", 4, "jona", "And the hard thing you take on to see if you can do it. Find that word too.",
       "Und die schwere Sache, die man annimmt, um zu sehen, ob man sie schafft. Finde auch dieses Wort.",
       [("hard", "schwer"), ("take on", "annehmen"), ("see", "sehen"), ("word", "Wort"), ("thing", "Sache"), ("find", "finde")],
       [slot("name-it", "g2u14.w.challenge")]),
    sc("ch14", 5, "tarik", "And all the stuff we need — balls, ropes, the sacks! One word for all of it. Find it!",
       "Und das ganze Zeug, das wir brauchen — Bälle, Seile, die Säcke! Ein Wort für alles. Finde es!",
       [("stuff", "Zeug"), ("balls", "Bälle"), ("ropes", "Seile"), ("sacks", "Säcke"), ("need", "brauchen"), ("word", "Wort"), ("find", "finde")],
       [slot("name-it", "g2u14.w.equipment")]),
    sc("ch14", 6, "narrator", "Then the noise peaks — a whistle, a cheer, a drum — and the gym door slams itself shut. The gym goes... blank.",
       "Dann erreicht der Lärm seinen Höhepunkt — eine Pfeife, ein Jubel, eine Trommel — und die Turnhallentür knallt von selbst zu. Die Turnhalle wird... leer.",
       [("noise", "Lärm"), ("peaks", "Höhepunkt"), ("whistle", "Pfeife"), ("cheer", "Jubel"), ("drum", "Trommel"), ("slams", "knallt zu"), ("blank", "leer"), ("gym", "Turnhalle"), ("door", "Tür"), ("itself", "von selbst")]),
    sc("ch14", 7, "emma", "It panicked. It swallowed the whole gym to hide in — and Pixel was SLEEPING in there!",
       "Sie hat Panik bekommen. Sie hat die ganze Turnhalle geschluckt, um sich zu verstecken — und Pixel hat da drin GESCHLAFEN!",
       [("panicked", "Panik bekommen"), ("swallowed", "geschluckt"), ("hide", "verstecken"), ("sleeping", "geschlafen"), ("whole", "ganze"), ("gym", "Turnhalle")]),
    sc("ch14", 8, "jona", "Nobody shouts. I go in first. I have been inside an empty thing — I know the way back out.",
       "Niemand schreit. Ich gehe zuerst hinein. Ich war in einem leeren Ding — ich kenne den Weg zurück nach draußen.",
       [("shouts", "schreit"), ("first", "zuerst"), ("inside", "drinnen"), ("empty", "leer"), ("way", "Weg"), ("out", "draußen"), ("nobody", "niemand"), ("know", "kenne"), ("thing", "Ding"), ("go", "gehe")]),
    sc("ch14", 9, "emma", "Have you ever done anything like this before? Say it right — and then GO.",
       "Hast du so etwas schon einmal gemacht? Sag es richtig — und dann GEH.",
       [("ever", "jemals"), ("before", "schon einmal"), ("say", "sag"), ("right", "richtig"), ("done", "gemacht")],
       [slot("fix-it", "g2u14.gi.present-perfect-ever-never.mc.001")]),
    sc("ch14", 10, "jona", "We have not lost anyone yet. Not one. Say it right!",
       "Wir haben noch niemanden verloren. Nicht einen. Sag es richtig!",
       [("lost", "verloren"), ("anyone", "irgendjemanden"), ("yet", "noch"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u14.gi.present-perfect-already-yet.cp.002")]),
    sc("ch14", 11, "narrator", "Movement words are the rope: walk, turn, climb, carry. Jona walks into the blank gym saying them — and the walls listen.",
       "Bewegungswörter sind das Seil: gehen, drehen, klettern, tragen. Jona geht in die leere Turnhalle und sagt sie — und die Wände hören zu.",
       [("movement", "Bewegung"), ("words", "Wörter"), ("rope", "Seil"), ("walk", "gehen"), ("turn", "drehen"), ("climb", "klettern"), ("carry", "tragen"), ("walls", "Wände"), ("listen", "hören zu"), ("blank", "leer"), ("gym", "Turnhalle"), ("saying", "sagt")]),
    sc("ch14", 12, "narrator", "He comes back out with a cat. The cat is FURIOUS and completely fine. Behind him, the gym redraws itself, wall by wall.",
       "Er kommt mit einer Katze wieder heraus. Die Katze ist WÜTEND und völlig in Ordnung. Hinter ihm zeichnet sich die Turnhalle neu, Wand für Wand.",
       [("cat", "Katze"), ("furious", "wütend"), ("completely", "völlig"), ("fine", "in Ordnung"), ("redraws", "zeichnet sich neu"), ("wall", "Wand"), ("behind", "hinter"), ("gym", "Turnhalle"), ("comes back", "kommt zurück")],
       [slot("recap", "g2u14.ci.the-rescue.mc.001")]),
    sc("ch14", 13, "jona", "It said sorry. In its way. It gave the gym back BEFORE I asked. ... We are nearly there, team.",
       "Sie hat sich entschuldigt. Auf ihre Art. Sie hat die Turnhalle zurückgegeben, BEVOR ich gefragt habe. ... Wir sind fast am Ziel, Team.",
       [("said sorry", "entschuldigt"), ("way", "Art"), ("gave", "zurückgegeben"), ("before", "bevor"), ("asked", "gefragt"), ("nearly", "fast"), ("team", "Team"), ("gym", "Turnhalle")]),
])
ci14 = ci("g2u14.ci.the-rescue.mc.001", "Who goes into the blank gym first?",
          "Jona.",
          ["Emma.", "Frau Berger.", "Tarik."],
          [("blank", "leer"), ("gym", "Turnhalle"), ("first", "zuerst"), ("goes", "geht")],
          "Wer kennt leere Dinge von innen?",
          "Jona geht zuerst hinein — er war selbst in einem leeren Ding und kennt den Weg zurück. Er holt Pixel heraus, und die leere Stelle gibt die Turnhalle von selbst zurück: Vertrauen, auf beiden Seiten."),

# ── ch15 · u15 "Klecks" — the finale ──
ch15 = ("Klecks", "Klecks", [
    sc("ch15", 1, "narrator", "The book nook, last week of school. The whole class is here. So is a pale patch by the shelf, pretending not to listen.",
       "Die Buchecke, letzte Schulwoche. Die ganze Klasse ist da. Und ein blasser Fleck am Regal, der so tut, als würde er nicht zuhören.",
       [("book nook", "Buchecke"), ("last", "letzte"), ("week", "Woche"), ("whole", "ganze"), ("pale", "blass"), ("patch", "Fleck"), ("shelf", "Regal"), ("pretending", "so tun als"), ("listen", "zuhören"), ("class", "Klasse"), ("school", "Schule")]),
    sc("ch15", 2, "jona", "You cannot un-erase a thing. But you can write the next thing. Today we write it a story of its own.",
       "Man kann etwas nicht ent-radieren. Aber man kann das Nächste schreiben. Heute schreiben wir ihr eine eigene Geschichte.",
       [("un-erase", "ent-radieren"), ("next", "das Nächste"), ("story", "Geschichte"), ("own", "eigene"), ("write", "schreiben"), ("today", "heute"), ("thing", "Ding")]),
    sc("ch15", 3, "emma", "Everyone gives words. Every single kid. Even the hamster sent one, and we are NOT reading it out.",
       "Alle geben Wörter. Jedes einzelne Kind. Sogar der Hamster hat eins geschickt, und wir lesen es NICHT vor.",
       [("everyone", "alle"), ("gives", "geben"), ("words", "Wörter"), ("single", "einzeln"), ("kid", "Kind"), ("hamster", "Hamster"), ("sent", "geschickt"), ("reading", "vorlesen"), ("even", "sogar")]),
    sc("ch15", 4, "tarik", "A story-creature needs care, like a pet! What do you do when a pet is hungry? Find the words!",
       "Ein Geschichten-Wesen braucht Pflege, wie ein Haustier! Was macht man, wenn ein Haustier Hunger hat? Finde die Wörter!",
       [("creature", "Wesen"), ("care", "Pflege"), ("pet", "Haustier"), ("hungry", "Hunger"), ("needs", "braucht"), ("words", "Wörter"), ("find", "finde"), ("story", "Geschichte")],
       [slot("name-it", "g2u15.w.to-feed-your-pet")]),
    sc("ch15", 5, "emma", "It will live in the book nook — so it needs a place for... its business. Find the word. Do not laugh.",
       "Es wird in der Buchecke wohnen — also braucht es einen Platz für... sein Geschäft. Finde das Wort. Nicht lachen.",
       [("live", "wohnen"), ("place", "Platz"), ("business", "Geschäft"), ("laugh", "lachen"), ("word", "Wort"), ("needs", "braucht"), ("find", "finde"), ("book nook", "Buchecke")],
       [slot("name-it", "g2u15.w.litter-tray")]),
    sc("ch15", 6, "tarik", "I love this plan. Say you love it too — the agreeing way! Find the words!",
       "Ich liebe diesen Plan. Sag, dass du ihn auch liebst — auf die Zustimm-Art! Finde die Wörter!",
       [("plan", "Plan"), ("agreeing", "zustimmen"), ("way", "Art"), ("words", "Wörter"), ("say", "sag"), ("find", "finde"), ("love", "lieben")],
       [slot("name-it", "g2u15.w.so-do-i")]),
    sc("ch15", 7, "narrator", "The class reads the story out, line by line. Every collected word from the whole year is in it — and every word lands on the pale patch like paint.",
       "Die Klasse liest die Geschichte vor, Zeile für Zeile. Jedes gesammelte Wort aus dem ganzen Jahr ist darin — und jedes Wort landet auf dem blassen Fleck wie Farbe.",
       [("reads", "liest"), ("line", "Zeile"), ("collected", "gesammelt"), ("year", "Jahr"), ("lands", "landet"), ("paint", "Farbe"), ("class", "Klasse"), ("story", "Geschichte"), ("word", "Wort"), ("whole", "ganze"), ("pale", "blass"), ("patch", "Fleck"), ("every", "jedes")]),
    sc("ch15", 8, "emma", "I take care of the words on Mondays. Say you do too. Say it right!",
       "Ich kümmere mich montags um die Wörter. Sag, dass du das auch machst. Sag es richtig!",
       [("take care", "sich kümmern"), ("Mondays", "montags"), ("words", "Wörter"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u15.gi.so-do-i.cp.003")]),
    sc("ch15", 9, "jona", "And I read to it in the evenings. Say it the agreeing way — all of you. Say it right!",
       "Und ich lese ihm abends vor. Sagt es auf die Zustimm-Art — ihr alle. Sag es richtig!",
       [("read to", "vorlesen"), ("evenings", "abends"), ("agreeing", "zustimmen"), ("way", "Art"), ("say", "sag"), ("right", "richtig")],
       [slot("fix-it", "g2u15.gi.so-do-i.cp.004")]),
    sc("ch15", 10, "narrator", "And where the pale patch was: a small, round, ink-black creature with one white spot, blinking at its own paws.",
       "Und wo der blasse Fleck war: ein kleines, rundes, tintenschwarzes Wesen mit einem weißen Fleck, das seine eigenen Pfoten anblinzelt.",
       [("round", "rund"), ("ink-black", "tintenschwarz"), ("creature", "Wesen"), ("white", "weiß"), ("spot", "Fleck"), ("blinking", "blinzelt"), ("paws", "Pfoten"), ("small", "klein"), ("own", "eigene"), ("pale", "blass"), ("patch", "Fleck")],
       [slot("recap", "g2u15.ci.klecks.mc.001")]),
    sc("ch15", 11, "blank", "...Klecks.",
       "...Klecks.",
       []),
    sc("ch15", 12, "narrator", "It named itself with a kept word. Of course it did. It has the best collection in the school.",
       "Es hat sich selbst benannt, mit einem aufgehobenen Wort. Natürlich. Es hat die beste Sammlung der Schule.",
       [("named", "benannt"), ("itself", "sich selbst"), ("kept", "aufgehoben"), ("collection", "Sammlung"), ("of course", "natürlich"), ("word", "Wort"), ("best", "beste"), ("school", "Schule")]),
    sc("ch15", 13, "finn", "A new keeper for the book! This is my favourite ending so far. And I have READ them all.",
       "Ein neuer Hüter für das Buch! Das ist mein Lieblingsende bisher. Und ich habe ALLE gelesen.",
       [("keeper", "Hüter"), ("favourite", "Lieblings-"), ("ending", "Ende"), ("so far", "bisher"), ("read", "gelesen"), ("book", "Buch"), ("new", "neu")]),
    sc("ch15", 14, "berger", "A class pet. How... unexpected. I will fetch the register and add — what IS it? Never mind. I will bring biscuits.",
       "Ein Klassentier. Wie... unerwartet. Ich hole das Klassenbuch und trage ein — was IST es denn? Egal. Ich bringe Kekse.",
       [("class pet", "Klassentier"), ("unexpected", "unerwartet"), ("fetch", "holen"), ("register", "Klassenbuch"), ("never mind", "egal"), ("biscuits", "Kekse"), ("bring", "bringe"), ("add", "eintragen")]),
    sc("ch15", 15, "narrator", "Pixel and Klecks ignore each other magnificently. The book sleeps on its shelf with a new last page — written by everyone. Klecks sleeps on the page.",
       "Pixel und Klecks ignorieren einander großartig. Das Buch schläft auf seinem Regal mit einer neuen letzten Seite — von allen geschrieben. Klecks schläft auf der Seite.",
       [("ignore", "ignorieren"), ("each other", "einander"), ("magnificently", "großartig"), ("sleeps", "schläft"), ("shelf", "Regal"), ("last", "letzte"), ("page", "Seite"), ("written", "geschrieben"), ("everyone", "alle"), ("book", "Buch"), ("new", "neu")]),
    sc("ch15", 16, "jona", "Two years ago I erased my way out of every picture. This year a whole class wrote something back in. ... Thank you. All of you.",
       "Vor zwei Jahren habe ich mich aus jedem Bild herausradiert. Dieses Jahr hat eine ganze Klasse etwas zurückgeschrieben. ... Danke. Euch allen.",
       [("years", "Jahre"), ("ago", "vor"), ("erased", "radiert"), ("picture", "Bild"), ("wrote", "geschrieben"), ("whole", "ganze"), ("class", "Klasse"), ("year", "Jahr"), ("something", "etwas")]),
])
ci15 = ci("g2u15.ci.klecks.mc.001", "What does the class give the blank?",
          "A story of its own.",
          ["A new school bag.", "A bowl of food.", "A place to hide."],
          [("class", "Klasse"), ("blank", "leere Stelle"), ("story", "Geschichte"), ("own", "eigene"), ("school bag", "Schultasche"), ("bowl", "Napf"), ("food", "Futter"), ("hide", "verstecken"), ("place", "Platz"), ("give", "geben"), ("new", "neu")],
          "Nicht Futter, nicht ein Versteck — was füllt eine leere Stelle?",
          "Die Klasse schreibt der leeren Stelle eine eigene Geschichte — jedes Kind gibt Wörter. Gefüllt mit Wörtern wird sie zu Klecks: dem Klassentier und dem neuen Hüter des Buchs."),

CHAPTERS = {"ch09": ch09, "ch10": ch10, "ch11": ch11, "ch12": ch12, "ch13": ch13, "ch14": ch14, "ch15": ch15}
CIS = [ci09[0] if isinstance(ci09, tuple) else ci09, ci10[0] if isinstance(ci10, tuple) else ci10,
       ci11[0] if isinstance(ci11, tuple) else ci11, ci12[0] if isinstance(ci12, tuple) else ci12,
       ci13[0] if isinstance(ci13, tuple) else ci13, ci14[0] if isinstance(ci14, tuple) else ci14,
       ci15[0] if isinstance(ci15, tuple) else ci15]

st = json.load(open(SP))
existing = {c["id"].split(".")[-1] for c in st["chapters"]}
for key in sorted(CHAPTERS):
    title_en, title_de, scenes = CHAPTERS[key]
    for i, s in enumerate(scenes):
        s["next"] = scenes[i + 1]["id"] if i + 1 < len(scenes) else None
    unit = int(key[2:])
    chap = {"id": f"{CH}.{key}", "unit": unit, "titleEn": title_en, "titleDe": title_de, "scenes": scenes}
    if key in existing:
        st["chapters"] = [chap if c["id"].endswith(key) else c for c in st["chapters"]]
    else:
        st["chapters"].append(chap)
st["chapters"].sort(key=lambda c: c["unit"])
json.dump(st, open(SP, "w"), ensure_ascii=False, indent=1)

co = json.load(open(CP))
have = {i["id"] for i in co["items"]}
for item in CIS:
    if item["id"] not in have:
        co["items"].append(item)
json.dump(co, open(CP, "w"), ensure_ascii=False, indent=1)
print(f"ch09–ch15 written ({sum(len(c[2]) for c in CHAPTERS.values())} scenes, {len(CIS)} ci items)")
